import assert from 'node:assert/strict';
import {test} from 'node:test';
import {haikuQualificationModel} from './model.mjs';
function setup(response){const calls=[],a={async http(id){calls.push(['reserve',id]);},async complete(id){calls.push(['complete',id]);}},m=haikuQualificationModel({authority:a,credential:'synthetic-only',pricingReviewedUntil:2000,clock:()=>1000,request:async(url,init)=>{calls.push(['request',url,JSON.parse(init.body)]);return response();}});return {m,calls};}
const ok=()=>Response.json({model:'claude-haiku-4-5-20251001',usage:{input_tokens:200000,output_tokens:800},content:[{type:'text',text:'synthetic'}]});
test('exact model and full-context maximum liability remain below reservation',async()=>{const {m,calls}=setup(ok),r=await m.invoke('synthetic',new AbortController().signal,'model_0001');assert.equal(r.actualMicrousd,204000);assert.equal(calls[0][0],'reserve');assert.equal(calls[1][2].max_tokens,800);assert.equal(calls[1][2].model,'claude-haiku-4-5-20251001');assert.equal(calls.at(-1)[0],'complete');});
test('oversized input and model disable prevent provider access',async()=>{const {m,calls}=setup(ok);await assert.rejects(m.invoke('x'.repeat(16001),new AbortController().signal,'model_0001'));assert.equal(calls.length,0);assert.equal(m.disable(),true);await assert.rejects(m.invoke('x',new AbortController().signal,'model_0001'));assert.equal(calls.length,0);});
test('unknown usage fails closed without retry',async()=>{const {m,calls}=setup(()=>Response.json({}));await assert.rejects(m.invoke('x',new AbortController().signal,'model_0001'));assert.equal(calls.filter(x=>x[0]==='request').length,1);});
test('price review must cover only a bounded current window',()=>{assert.throws(()=>haikuQualificationModel({authority:{},credential:'x',pricingReviewedUntil:0}));});
