export interface PrimaryBootstrapInput {
  agentName?: string;
  instructions: string;
  model?: string;
}

/** Generate the one-time durable-primary initialization input for a deployment. */
export function generatePrimaryBootstrapSource(input: PrimaryBootstrapInput): string {
  return `/** Generated by MyEve Builder — do not edit. */
export const PRIMARY_AGENT_BOOTSTRAP = {
  name: process.env.NEXT_PUBLIC_AGENT_NAME?.trim() || ${JSON.stringify(input.agentName?.trim() || "MyEve")},
  role: "Primary personal agent",
  description: "Helps the owner interpret goals, plan work, focus, and review progress.",
  instructions: ${JSON.stringify(input.instructions)},
  preferredModel: ${JSON.stringify(input.model ?? "anthropic/claude-sonnet-5")},
} as const;
`;
}
