"use client";
import { Badge, Button, Loader } from "@cloudflare/kumo";
import { useCallback, useEffect, useState } from "react";
import type { ApprovalRequestView } from "@/lib/approvals";

export function ApprovalCenterPanel(){
  const [items,setItems]=useState<ApprovalRequestView[]|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState<string|null>(null);
  const load=useCallback(async()=>{try{const response=await fetch("/api/approvals",{cache:"no-store"});if(!response.ok)throw new Error();const body=await response.json() as {approvals:ApprovalRequestView[]};setItems(body.approvals);setError(null);}catch{setError("Approval requests could not be loaded. Refresh before authorizing anything.");}},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(timer);},[load]);
  async function decide(item:ApprovalRequestView,decision:"approved"|"denied"){setBusy(item.id);try{const response=await fetch(`/api/approvals/${encodeURIComponent(item.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision,bindingHash:item.bindingHash})});if(!response.ok){const body=await response.json().catch(()=>null) as {error?:{message?:string}}|null;throw new Error(body?.error?.message??"This approval is no longer valid.");}await load();}catch(cause){setError(cause instanceof Error?cause.message:"Approval decision failed.");}finally{setBusy(null);}}
  if(items===null&&!error)return <div className="flex justify-center py-16"><Loader size={18}/></div>;
  const pending=items?.filter(item=>item.status==="pending")??[];const history=items?.filter(item=>item.status!=="pending")??[];
  return <div><div><h3 className="text-base font-semibold">Approval Center</h3><p className="mt-1 text-sm text-kumo-subtle">Authorize one exact action. Changed parameters or expired requests cannot reuse a decision.</p></div>
    {error&&<div className="mt-4 rounded-xl border border-kumo-danger/25 bg-kumo-danger/5 p-3 text-sm">{error}</div>}
    <section className="mt-6"><h4 className="text-sm font-semibold">Needs your decision</h4>{pending.length===0?<div className="mt-3 rounded-2xl border border-dashed border-kumo-hairline p-8 text-center text-sm text-kumo-subtle">No approvals are waiting.</div>:<ul className="mt-3 grid gap-3">{pending.map(item=><li key={item.id} className="rounded-2xl border border-kumo-hairline p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.action}</p><Badge variant="secondary">{item.risk} risk</Badge><Badge variant="secondary">{item.actionClass}</Badge></div><p className="mt-2 text-sm">{item.prompt}</p><p className="mt-2 text-xs text-kumo-subtle">Resource: {item.resource??"Not specified"} · Capability: {item.capabilityId??"Not specified"} · Expires {new Date(item.expiresAt).toLocaleString()}</p>{item.effects.length>0&&<p className="mt-2 text-xs">Effects: {item.effects.join(" · ")}</p>}</div><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={busy===item.id} onClick={()=>void decide(item,"denied")}>Deny</Button><Button size="sm" disabled={busy===item.id} onClick={()=>void decide(item,"approved")}>Approve exact action</Button></div></div><details className="mt-3 text-xs"><summary className="cursor-pointer text-kumo-subtle">Safe parameter summary</summary><pre className="mt-2 overflow-x-auto rounded-xl bg-kumo-tint p-3">{JSON.stringify(item.parameters,null,2)}</pre></details></li>)}</ul>}</section>
    {history.length>0&&<section className="mt-8"><h4 className="text-sm font-semibold">Decision history</h4><ul className="mt-3 divide-y divide-kumo-hairline rounded-2xl border border-kumo-hairline px-4">{history.slice(0,30).map(item=><li key={item.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium">{item.action}</p><p className="mt-1 text-xs text-kumo-subtle">{item.decidedAt?new Date(item.decidedAt).toLocaleString():new Date(item.expiresAt).toLocaleString()}</p></div><Badge variant={item.status==="denied"?"destructive":"secondary"}>{item.status}</Badge></li>)}</ul></section>}
  </div>;
}
