import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {z} from 'zod';
const m=vi.hoisted(()=>({available:true,mode:'LOCAL_FIXTURE',gateway:vi.fn(),binding:vi.fn()}));
vi.mock('../../lib/capability-registry.ts',()=>({checkCapabilityAvailability:()=>({status:m.available?'available':'disabled'})}));
vi.mock('../../lib/engineering/factory-api.ts',()=>({factoryAction:vi.fn(),factoryActionSchema:z.object({})}));
vi.mock('../../lib/engineering/factory-routing.ts',()=>({factoryConfig:async()=>({engineering:{ownerId:'owner',agentId:'sofie'},connection:{factoryId:'local',qualification:{mode:m.mode}}})}));
vi.mock('../lib/engineering-knowledge-binding.ts',()=>({assertEngineeringKnowledgeWorkBinding:m.binding}));
vi.mock('../lib/session-settings.ts',()=>({resolveSessionAgent:async()=>({id:'sofie',isPrimary:true})}));
vi.mock('../lib/action-context.ts',()=>({toolActionRequest:async()=>({})}));
vi.mock('../../lib/action-gateway.ts',()=>({ActionGateway:class{execute=m.gateway},consumeActionAuthority:vi.fn(),consumeProviderAuthority:vi.fn()}));
import definition from './engineering_factory.ts';
const context=()=>({session:{id:'current',auth:{current:{principalId:'owner',principalType:'user',attributes:{owner:'true',myeveEngineeringWorkId:'11111111-1111-4111-8111-111111111111'}}}}});
const discover=(ctx:any)=>definition.events['step.started']!({},ctx) as Promise<any>;
beforeEach(()=>{vi.clearAllMocks();m.available=true;m.mode='LOCAL_FIXTURE';vi.stubEnv('MYEVE_ENGINEERING_MODE','dogfood');vi.stubEnv('MYEVE_FACTORY_CONFIG','/tmp/test-only-factory.json');vi.stubEnv('VERCEL_ENV','preview');});afterEach(()=>vi.unstubAllEnvs());
it.each(['guest','delegated','parent','non-owner','agent'])('does not expose Factory execution to %s context',async kind=>{const ctx:any=context();if(kind==='guest')ctx.session.auth.current.attributes.role='guest';if(kind==='delegated')ctx.session.auth.current.attributes.myeveRoleId='role';if(kind==='parent')ctx.session.parent={};if(kind==='non-owner')ctx.session.auth.current.attributes.owner='false';if(kind==='agent')ctx.session.auth.current.principalType='agent';expect(await discover(ctx)).toBeNull();expect(m.gateway).not.toHaveBeenCalled();});
it('rechecks capability availability at execution',async()=>{const ctx=context(),tool=await discover(ctx);m.available=false;await expect(tool.execute({},ctx)).rejects.toThrow(/unavailable/);expect(m.gateway).not.toHaveBeenCalled();});
it('rejects live qualification before the action gateway',async()=>{const ctx=context(),tool=await discover(ctx);m.mode='LIVE';await expect(tool.execute({},ctx)).rejects.toThrow(/separate authorization/);expect(m.gateway).not.toHaveBeenCalled();});
it('rejects changed owner identity after discovery',async()=>{const ctx:any=context(),tool=await discover(ctx);ctx.session.auth.current={...ctx.session.auth.current,principalId:'other-owner'};await expect(tool.execute({},ctx)).rejects.toThrow(/owner selected Work/);expect(m.gateway).not.toHaveBeenCalled();});
it('does not expose the tool in production',async()=>{vi.stubEnv('VERCEL_ENV','production');expect(await discover(context())).toBeNull();});
