"use client";
import { useCallback, useEffect, useState } from "react";
import { ProductShell, ResourceState } from "@/components/owner/product-shell";
const labels={OWNER_PRIVATE:'Private',BUSINESS_SHARED:'Shared with business',WORK_SCOPED:'Shared for this Work'};
type Resource={kind:string;id:string;owner_id?:string;document:Record<string,unknown>;revision_hash:string;scope:keyof typeof labels;grant_id?:string};
type Grant={id:string;kind:string;resource_id:string;scope:keyof typeof labels;revoked_at:string|null};
type Decision={superseded_at:string|null;effect:Record<string,unknown>;work_id:string;id:string;effect_hash:string;policy:string;approved_a:boolean;approved_b:boolean;denied:boolean;expires_at:string};
type Data={owner:string;configured:boolean;partnership:{accepted_a:boolean;accepted_b:boolean}|null;private:Resource[];shared:Resource[];grants:Grant[];decisions:Decision[]};
export default function BusinessPage(){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [policy,setPolicy]=useState('BOTH_OWNERS'),[operation,setOperation]=useState('execute_native');
 const [question,setQuestion]=useState(''),[answer,setAnswer]=useState('');
 const [work,setWork]=useState(''),[selected,setSelected]=useState(''),[scope,setScope]=useState<'BUSINESS_SHARED'|'WORK_SCOPED'>('BUSINESS_SHARED');
 const refresh=useCallback(async()=>{setLoading(true);setError(null);try{const query=work?`?workId=${encodeURIComponent(work.split('|')[1])}&workOwner=${encodeURIComponent(work.split('|')[0])}`:'';const response=await fetch('/api/business'+query,{cache:'no-store'});const body=await response.json();if(!response.ok)throw Error(body.error);setData(body);}catch(e){setError(e instanceof Error?e.message:'Could not load sharing.');}finally{setLoading(false);}},[work]);
 useEffect(()=>{void refresh();},[refresh]);
 async function command(operation:string,value?:unknown){setBusy(true);setNotice('');setError(null);try{const response=await fetch('/api/business',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({operation,value})});const body=await response.json();if(!response.ok)throw Error(body.error);setNotice('Saved. Scope will be checked again whenever information is read.');await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not save sharing.');}finally{setBusy(false);}}
 async function ask(){setBusy(true);setAnswer('');setError(null);try{const response=await fetch('/api/business/ask',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question,context:work?{scope:'WORK_SCOPED',workOwner:work.split('|')[0],workId:work.split('|')[1]}:{scope:'BUSINESS_SHARED'}})});const body=await response.json();if(!response.ok)throw Error(body.error);setAnswer(body.answer);}catch(e){setError(e instanceof Error?e.message:'Sofie is unavailable.');}finally{setBusy(false);}}
 const active=data?.partnership?.accepted_a&&data?.partnership?.accepted_b;
 const resource=data?.private.find(r=>`${r.kind}|${r.id}`===selected);
 const works=data?.shared.filter(r=>r.kind==='WORK')??[];
 return <ProductShell title="Our business" description="Your private context stays yours. Share exact information with your partner or for one Work.">
  <ResourceState loading={loading} error={error} refresh={()=>void refresh()}/>
  {notice&&<p role="status">{notice}</p>}
  {data&&<>
   <section className="owner-card"><h2>Business sharing</h2><p>Signed in as {data.owner}. Conversations, Inbox, preferences and connections remain Private. Sharing does not authorize execution or transfer credentials.</p>
    {!data.configured?<p>Partner sign-in is not configured for this deployment.</p>:<><p>{active?'Both partners have accepted.': 'Both partners must accept before shared information becomes available.'}</p><button disabled={busy} onClick={()=>void command('accept')}>Accept business sharing</button> <button disabled={busy||!data.partnership} onClick={()=>void command('leave')}>Leave and revoke access</button></>}
   </section>
   <section className="owner-card"><h2>Share information</h2><p>Review the exact content below. Later revisions require a new explicit share. Sharing a Goal does not share its Tasks, Files or conversations.</p>
    <label>Private item <select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose an item</option>{data.private.map(r=><option key={r.kind+r.id} value={`${r.kind}|${r.id}`}>{r.kind}: {String(r.document.title??r.document.filename??r.document.statement??r.document.content??r.id).slice(0,90)}</option>)}</select></label>
    {resource&&<pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(resource.document,null,2)}</pre>}
    <label>Share with <select value={scope} onChange={e=>setScope(e.target.value as typeof scope)}><option value="BUSINESS_SHARED">Shared with business</option><option value="WORK_SCOPED">Shared for this Work</option></select></label>
    <label>Work context <select value={work} onChange={e=>{setAnswer('');setWork(e.target.value);}}><option value="">Business context</option>{works.map(r=><option key={r.id} value={`${r.owner_id}|${r.id}`}>{String(r.document.title)}</option>)}</select></label>
    {scope==='WORK_SCOPED'&&<p>Access expires after one hour, when this Work ends or changes version, or when you revoke it—whichever happens first.</p>}
    <button disabled={busy||!active||!resource||(scope==='WORK_SCOPED'&&(!work||!['MEMORY','KNOWLEDGE','FILE'].includes(resource.kind)))} onClick={()=>resource&&void command('share',{kind:resource.kind,id:resource.id,revisionHash:resource.revision_hash,scope,...(scope==='WORK_SCOPED'?{workOwner:work.split('|')[0],workId:work.split('|')[1],expiresAt:new Date(Date.now()+3600000).toISOString()}:{})})}>Share reviewed content</button>
   </section>
   <section className="owner-card"><h2>{work?'Shared for this Work':'Shared with business'}</h2>{!data.shared.length&&<p>Nothing is shared in this context.</p>}{data.shared.map(r=><article key={r.grant_id}><h3>{r.kind} · {labels[r.scope]}</h3><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(r.document,null,2)}</pre>{r.kind==='FILE'&&<a href={`/api/business/files/${encodeURIComponent(r.id)}?owner=${encodeURIComponent(r.owner_id??'')}${work?`&workOwner=${encodeURIComponent(work.split('|')[0])}&workId=${encodeURIComponent(work.split('|')[1])}`:''}`}>Download shared file</a>}</article>)}</section>
   <section className="owner-card"><h2>Ask Sofie in this context</h2><p>Sofie receives only the selected shared evidence and this question. This answer is not saved as shared Knowledge or private Memory.</p><label>Your question <textarea value={question} maxLength={4000} onChange={e=>setQuestion(e.target.value)}/></label><button disabled={busy||!active||!question.trim()} onClick={()=>void ask()}>Ask Sofie</button>{answer&&<p style={{whiteSpace:'pre-wrap'}} role="status">{answer}</p>}</section>
   <section className="owner-card"><h2>Your sharing history</h2>{!data.grants.length&&<p>You have not shared anything.</p>}{data.grants.map(g=><p key={g.id}>{g.kind} {g.resource_id} · {labels[g.scope]} {g.revoked_at?'— Revoked':<button disabled={busy} onClick={()=>void command('revoke',g.id)}>Revoke</button>}</p>)}</section>
   <section className="owner-card"><h2>Shared decisions</h2><p>Each decision is tied to an exact effect and Work revision. Approval does not grant credentials or bypass the executor’s existing checks.</p><label>Approval needed from <select value={policy} onChange={e=>setPolicy(e.target.value)}><option value="BOTH_OWNERS">Both partners</option><option value="OWNER_A">Partner A</option><option value="OWNER_B">Partner B</option><option value="EITHER_OWNER">Either partner</option></select></label><label>Effect for selected Work <select value={operation} onChange={e=>setOperation(e.target.value)}><option value="execute_native">Bounded native execution</option><option value="execute_factory">Bounded MyFactory execution</option><option value="pause">Pause</option><option value="resume">Resume</option><option value="cancel">Cancel</option><option value="reopen">Reopen</option></select></label><button disabled={busy||!work||work.split('|')[0]!==data.owner} onClick={()=>{const current=works.find(r=>r.id===work.split('|')[1]);if(current)void command('request_decision',{workOwner:data.owner,workId:current.id,effect:operation.startsWith('execute_')?{operation}:{operation,expectedVersion:current.document.version},policy,expiresAt:new Date(Date.now()+3600000).toISOString()});}}>Request exact Work decision</button>{!data.decisions.length&&<p>No shared decisions to review.</p>}{data.decisions.map(d=><article key={d.id}><p>{d.policy.replaceAll('_',' ')} · {d.superseded_at?'Superseded':d.denied?'Denied':`A: ${d.approved_a?'approved':'pending'}; B: ${d.approved_b?'approved':'pending'}`}</p><pre style={{whiteSpace:'pre-wrap'}}>Work: {d.work_id}{'\n'}{JSON.stringify(d.effect,null,2)}</pre><p style={{overflowWrap:'anywhere'}}>Exact effect: {d.effect_hash}</p><button disabled={busy||!!d.superseded_at||d.denied||Date.parse(d.expires_at)<=Date.now()} onClick={()=>void command('decide',{id:d.id,effectHash:d.effect_hash,approve:true})}>Approve exact effect</button> <button disabled={busy||!!d.superseded_at||d.denied} onClick={()=>void command('decide',{id:d.id,effectHash:d.effect_hash,approve:false})}>Deny</button></article>)}</section>
  </>}
 </ProductShell>;
}
