const fs=require('node:fs');
const path=require('node:path');
const {createHash}=require('node:crypto');
const {execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'../../../..');
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
// Synthetic evidence only. The Next-generated next-env.d.ts is excluded from
// source cleanliness because Next changes its development type-cache path.
exports.record=async function record(page,file,fixture,identity={}){
 const git=(...args)=>execFileSync('git',args,{cwd:root,encoding:'utf8'}).trim();
 const sourceSha=git('rev-parse','HEAD');
 const dirty=git('diff','--name-only','HEAD','--','.',':(exclude)apps/eve/next-env.d.ts').split('\n').filter(Boolean);
 const fixtureDir=path.join(root,'apps/eve/test',fixture);
 const fixtures=Object.fromEntries(fs.readdirSync(fixtureDir).filter(n=>/\.(ts|cjs)$/.test(n)).sort().map(n=>[n,sha(fs.readFileSync(path.join(fixtureDir,n)))]));
 const data={sourceSha,sourceDirtyPaths:dirty,authoritative:dirty.length===0,fixture,fixtures,
  owner:fixture==='owner-ux'?'11111111-1111-4111-8111-111111111111':'disposable owner generated by the signed journey fixture',
  browser:page.context().browser().version(),platform:process.platform,viewport:page.viewportSize(),
  featurePolicy:fixture==='owner-ux'?'synthetic private-alpha; no execution policy installed':'synthetic external-alpha policy; intercepted no-paid provider; isolated Factory fixture',
  ...identity,screenshotSha256:sha(fs.readFileSync(file)),capturedAt:new Date().toISOString()};
 fs.writeFileSync(file+'.provenance.json',JSON.stringify(data,null,2)+'\n');
};
